config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :books do
    resource :favorites,only: [:create, :destroy]
    resources :book_comments,only: [:create, :destroy]
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  root 'homes#top'
  get "home/about" => "homes#about"

  get "/search" => "search#search"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
	end

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follow_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

    def followed_by?(user)
     follow_user.include?(user)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_params)
    @book_comment.book_id = @book.id
    @showbook = Book.new
    @book_comment.save
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    @book = Book.find(params[:book_id])
  end

   private

  def book_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def show
    @book = Book.find(params[:id])
    @showbook = Book.new
    @book_comment = BookComment.new
    @books = Book.all
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    # user_idの情報はフォームから送られていないので、追加で代入してあげないといけない
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id != current_user.id
      redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    # favorite = Favorite.new
    # favorite.book_id = @book_id
    # favorite.user_id = current_user

    # favorite = Favorite.new(book_id: @book.id, user_id: current_user.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.follower.build(followed_id: params[:user_id])
    follow.save
    redirect_to request.referer
  end

  def destroy
    follow = current_user.follower.find_by(followed_id: params[:user_id])
    follow.destroy
    redirect_to request.referer
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def search
    # binding.pry
    @model = params["search"]["model"]
    @value = params["search"]["value"]
    @how = params["search"]["how"]
    @datas = search_for(@how,@model,@value)
  end

  private

  def match(model, value)
    if model == 'user'
      User.where(name: value)
    elsif model == 'book'
      # Book.find(1)
      # Book.find_by(title: value)
      Book.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'User'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}%")
    end
  end

  def search_for(how, model, value)
    case how
    when 'match'
      match(model, value)
    when 'forward'
      forward(model, value)
    when 'backward'
      backward(model, value)
    when 'partical'
      partical(model, value)
    end
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def follows
    user = User.find(params[:id])
    @users = user.follow_user
  end

  def followers
    user = User.find(params[:id])
    @users = user.follower_user
  end


  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_book_comments.html.erb
<% book.book_comments.each do |book_comment| %>
  <tr>
  	<td><%= image_tag('no-image-icon') %>
        <%= link_to user_path(book_comment.user) do %>
          <%= book_comment.user.name %>
        <% end %></td>
    <td><%= book_comment.comment %></td>
      <% if book_comment.user == current_user %>
    <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger destroy_book_#{@book.id}", remote: true %>
    </td>
      <% end %>
  </tr>
<% end %>

app/views/book_comments/create.js.erb
$(".comment-index").html("<%= j(render 'book_comments', book: @book) %>");
$("textarea").val('')

app/views/book_comments/destroy.js.erb
$(".comment-index").html("<%= j(render 'book_comments', book: @book) %>");

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td class="favorite-btn_<%= book.id %>"><%= render 'favorites/favorites', book: book %></td>
        <td> <p><%= link_to "コメント数：#{book.book_comments.count} ", book_path(book.id) %></p></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
      <%= render 'layouts/errors', obj: @book %>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td class="favorite-btn_<%= book.id %>"><%= render 'favorites/favorites', book: book %></td>
        <td> <p><%= link_to "コメント数：#{book.book_comments.count} ", book_path(book.id) %></p></td>
      </tr>
    <% end %>
  </tbody>
</table>


    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @showbook %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <% if @book.user_id == current_user.id %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>

        <td class="favorite-btn_<%= @book.id %>"><%= render 'favorites/favorites', book: @book %></td>

          <td>コメント数：<%= @book.book_comments.count %></td>
        </tr>
      </table>
        <%= render 'layouts/errors', obj: @book_comment %>

  		<table class='comment-index'>
  		   <%= render 'book_comments/book_comments', book: @book %>
  		</table>
  		<div class="new-comment">
        <%= form_with(model:[@book, @book_comment], remote: true) do |f| %>
          <%= f.text_area :comment, size: "100x5",placeholder: "コメントをここに" %>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/_favorites.html.erb
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete, remote: true  do %>
      ♥<%= book.favorites.count %>
      <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), method: :post, remote: true  do %>
      ♡<%= book.favorites.count %>
      <% end %>
  <% end %>

app/views/favorites/create.js.erb
$(".favorite-btn_<%= @book.id %>").html("<%= j(render 'favorites', book: @book) %>");

app/views/favorites/destroy.js.erb
$(".favorite-btn_<%= @book.id %>").html("<%= j(render 'favorites', book: @book) %>");

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/search/search.html.erb
<div class="container">
  <div class="col-xs-12">
    <% if @model == "user" %>
    <h2>Users search for '<%= @value %>'</h2>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
                <th>Introduction</th>
            </tr>
        </thead>
    <% @datas.each do |user| %>
        <tbody>
            <tr>
                <th>
                    <%= attachment_image_tag(user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40') %>
                </th>
                <th>
                   <%= link_to user_path(user) do %>
                   <%= user.name %>
                   <% end %>
                </th>
                <th>
                    <%= user.introduction %>
                </th>
            </tr>
        </tbody>
    <% end %>
    <% elsif @model == "book" %>
    <h2>Books search for '<%= @value %>'</h2>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
            </tr>
        </thead>
        <% @datas.each do |book| %>
        <tbody>
            <tr>
                <th>
                    <%= attachment_image_tag(book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40') %>
                </th>
                <th>
                   <%= link_to book_path(book) do %>
                   <%= book.title %>
                   <% end %>
                </th>
                <th>
                    <%= book.body %>
                </th>
            </tr>
        </tbody>
        <% end %>
    <% end %>
    </table>
  </div>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= "フォロー数: #{user.follower.count}" %></td>
        <td><%= "フォロワー数: #{user.followed.count}" %></td>

        <% if current_user != user %>
          <% if current_user.followed_by?(user) %>
            <td><%=link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></td>
          <% else %>
            <td><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
          <% end %>
        <% end %>

        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to follows_user_path(user) do %>
          <%= user.follower.count %>
        <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to followers_user_path(user) do %>
          <%= user.followed.count %>
        <% end %>
    </th>
  </tr>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-lg-12'>
      <h1>Follower Users</h1>
      <table class='table'>
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
            <td><%= user.name %></td>
            <td>フォロー数：<%= user.followed.count %></td>
            <td>フォロワー数：<%= user.follower.count %></td>
            <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/follows.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-lg-12'>
      <h1>Follow Users</h1>
      <table class='table'>
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
          <% if @users.present? %>
            <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
              <td><%= user.name %></td>
              <td>フォロー数：<%= user.followed.count %></td>
              <td>フォロワー数：<%= user.follower.count %></td>
              <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
            </tr>
            <% end %>
            <% else %>
              <td>ユーザーはいません</td>
          <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <table class='table'>
        <tr><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
        <tr>
	       <th>name</th>
	       <th><%= @user.name %></th>
        </tr>
        <tr>
	        <th>introduction</th>
	        <th><%= @user.introduction %></th>
        </tr>
        <tr>
          <th>follows</th>
          <th><%= link_to follows_user_path do %>
                <%= @user.follower.count %>
              <% end %>
          </th>
        </tr>
        <tr>
          <th>followers</th>
          <th><%= link_to followers_user_path do %>
                <%= @user.followed.count %>
              <% end %>
          </th>
        </tr>
        <% if current_user != @user %>
          <% if current_user.followed_by?(@user) %>
            <th><%=link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %></th>
          <% else %>
            <th><%=link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %></th>
          <% end %>
        <% end %>
      </table>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>